version: '3'
services:

  galaxy:
    image: "naturalis/galaxy:latest"
    volumes:
    - "${LOCAL_GENBANK_PATH:-/data/galaxy/GenBank}:/home/galaxy/GenBank"
    - "${LOCAL_EXTRAREF_PATH:-/data/galaxy/ExtraRef}:/home/galaxy/ExtraRef"
    - "/var/run/docker.sock:/var/run/docker.sock"
    env_file:
      - .env
    links:
      - "galaxy-database:db"
    networks:
      - default
      - web
    labels:
      - "traefik.backend=naturalis-galaxy"
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.port=8080"
      - ${GALAXY_URL_CONFIG:-traefik.frontend.rule=Host:galaxy.naturalis.nl}

  galaxy-database:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_ENV_POSTGRES_PASSWORD:-dbpassword}
    networks:
      - default
    volumes:
    - "${LOCAL_DB_PATH:-/data/galaxy-postgres-data}:/var/lib/postgresql/data"

  traefik:
    image: traefik:1.4.5
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${TRAEFIK_TOML_FILE:-./traefik.dev.toml}:/traefik.toml
      - ${ACME_JSON:-./acme.json}:/acme.json
    container_name: traefik

# run docker network create web before
networks:
  web:
    external: true


