version: '3'
services:

  galaxy:
    image: "naturalis/galaxy:latest"
    volumes:
    - "/data/galaxy/GenBank/:/home/galaxy/GenBank"
    - "/data/galaxy/ExtraRef/:/home/galaxy/ExtraRef"
    - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      URL_USEARCH: "http://drive5.com/cgi-bin/upload3.py?license=<your license key>"
      URL_UNITE: "https://unite.ut.ee/sh_files/sh_general_release_20.11.2016.zip"
      URL_SILVA: "https://www.arb-silva.de/fileadmin/silva_databases/current/Exports/SILVA_128_LSURef_tax_silva.fasta.gz"
      DB_ENV_POSTGRES_PASSWORD: "98dkk398910askks_all"
      UPDATE_GENBANK: "no"
      UPDATE_TAXA: "no"
    links:
      - "galaxy-database:db"
    networks:
      - default
      - web
    labels:
      - "traefik.backend=naturalis-galaxy"
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.port=8080"
      - ${GALAXY_URL_CONFIG:-traefik.frontend.rule=Host:galaxy.naturalis.nl}

  galaxy-database:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD: "98dkk398910askks_all"
    networks:
      - default
    volumes:
      - "/data/galaxy-postgres-data:/var/lib/postgresql/data"

  traefik:
    image: traefik:1.4.5
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${TRAEFIK_TOML_FILE:-./traefik.dev.toml}:/traefik.toml
      - ${ACME_JSON:-./acme.json}:/acme.json
    container_name: traefik

# run docker network create web before
networks:
  web:
    external: true


